version: "3.9"

services:
  backend:
    depends_on:
      - ref_shel_db
    container_name: springboot-ref-shel
    image: springboot-app
    ports:
      - "8081:8081"
    build:
      context: ../backend/RefugeeShelter
      dockerfile: Dockerfile

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ref_shel_db:5432/ref_shel
      - SPRING_DATASOURCE_USERNAME=akrik
      - SPRING_DATASOURCE_PASSWORD=akrik
      - SERVER_PORT=8081

  backend_2:
    depends_on:
      - ref_shel_db
    container_name: springboot-ref-shel_2
    image: springboot-app
    ports:
      - "8082:8082"
    build:
      context: ../backend/RefugeeShelter
      dockerfile: Dockerfile

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ref_shel_db:5432/ref_shel
      - SPRING_DATASOURCE_USERNAME=akrik
      - SPRING_DATASOURCE_PASSWORD=akrik
      - SERVER_PORT=8082

  backend_3:
    depends_on:
      - ref_shel_db
    container_name: springboot-ref-shel_3
    image: springboot-app
    ports:
      - "8083:8083"
    build:
      context: ../backend/RefugeeShelter
      dockerfile: Dockerfile

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ref_shel_db:5432/ref_shel
      - SPRING_DATASOURCE_USERNAME=akrik
      - SPRING_DATASOURCE_PASSWORD=akrik
      - SERVER_PORT=8083

  ref_shel_db:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_DB: "ref_shel"
      POSTGRES_USER: "akrik"
      POSTGRES_PASSWORD: "akrik"
    ports:
      - "5432:5432"
    volumes:
      - ref_shel_db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./templates:/etc/nginx/templates
      - ./nginx.conf:/Users/akrik/Desktop/iu7-web/nginx/nginx.conf
      # - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=refshel.com
      - NGINX_PORT=80
volumes:
  ref_shel_db:
    driver: local
