version: '3.9'

services:
    ref_shel_db:
        image: 'postgres:latest'
        restart: always
        environment:
            POSTGRES_DB: "ref_shel"
            POSTGRES_USER: "akrik"
            POSTGRES_PASSWORD: "akrik"
        ports:
            - '5432:5432'
        volumes:
            - ref_shel_db:/var/lib/postgresql/data

volumes:
    ref_shel_db:
        driver: local
